### ISSUE TITLE
ClojureScript repl is not working

### ISSUE THREAD

**Issue by borkdude** [borkdude/lein2boot#1]
When I connect to the running nrepl server, I should be able to do the following to get ClojureScript REPL:

```
(ns boot.user)
(start-repl)
```

**Comment by martinklepsch** [comment]
Working for me: 
1. call `boot dev` in one terminal window
2. open another and run `boot repl --client`
3. in the repl run  `(start-repl)`
4. open http://localhost:3000
5. in cljs REPL run `(+ 1 1)`

**Comment by borkdude** [comment]
@martinklepsch Thanks. I was misled, because I did not get autocompletion in CIDER for start-server!
